CREATE TABLE IF NOT EXISTS etudiant (
    id INT(10) PRIMARY KEY AUTO_INCREMENT,
    prenom VARCHAR(100) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    departement VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);
